### ISSUE TITLE
Call to a member function map() on null 

### ISSUE THREAD

**Issue by danielnisbet** [sortarad/quickbrownfox#2]
I'm running a pretty vanilla install of Statamic and inserted {{ quick_brown_fox :from="fonts" size="30" }} into one of my template files. Asset container titled "fonts" has been created with one OTF file in there. Additionally, using {{ quick_brown_fox from="fonts" size="30" }} returns a similar error, except the error is a for a string instead of NULL.

Not seeing much in the documentation to know if I'm missing a step or not. Alpine.js is installed.

**Comment by Mamaduka** [comment]
Hi @danielnisbet,

Thanks for reporting the issue.

I was able to reproduce the bug on the collection template where the entry doesn't have any fonts. I pushed the fix, and now the tag won't generate an error when fonts are missing.

You should always use a colon with the `:from` parameter, so Statamic knows, to resolve it from the context.

P.S. You can use any name for Fonts asset container. Just make sure that you provide the same **Handle** in the `:from` parameter.

**Comment by danielnisbet** [comment]
Thanks all. So am I understanding that I have to add an Assets field to the entry and then populate it that way to work? I did try that (with field name "font_preview" and linked only to my "fonts" container), and I'm seeing the same error.

**Comment by Mamaduka** [comment]
> So am I understanding that I have to add an Assets field to the entry and then populate it that way to work?
Yes, that's correct.

@danielnisbet Have tested with the latest changes?

Also attaching a screenshot of my test assets field.
<img width="1068" alt="Screenshot-alrwo" src="https://user-images.githubusercontent.com/240569/106302077-eb185900-6271-11eb-9cda-fc621ab7c69c.png">

**Comment by danielnisbet** [comment]
Pulled the latest changes and attaching what I have and see now!

![Screen Shot 2021-01-29 at 10 43 27](https://user-images.githubusercontent.com/72559635/106302728-f1311a00-621e-11eb-9dac-6560c2f9ea4e.jpg)
![Screen Shot 2021-01-29 at 10 43 04](https://user-images.githubusercontent.com/72559635/106302730-f1c9b080-621e-11eb-80f2-e0208b683e77.jpg)
![Screen Shot 2021-01-29 at 10 42 57](https://user-images.githubusercontent.com/72559635/106302732-f1c9b080-621e-11eb-82d0-d1d4740d2a90.jpg)

**Comment by Mamaduka** [comment]
@danielnisbet thanks for the more details.

I was able to reproduce the latest error by using the new Assets Container.

Then was able to resolve it by setting "File Driver" -> "Disk" to `assets` instead of the `local` (See attached screenshot).

Currently, I'm not sure why this is an issue, but this should work as a temp solution.

@nickhamze let's create a separate issue to make sure our tag works with different disks.

<img width="906" alt="Screenshot-zsf0r" src="https://user-images.githubusercontent.com/240569/106306541-a5f72580-6277-11eb-81c0-53e32f435be3.png">

**Comment by danielnisbet** [comment]
Ah—that didn't even cross my mind when I set this up! The Fonts container I'm running is set up through DigitalOcean spaces (which is just an S3 connection).

**Comment by danielnisbet** [comment]
And a quick edit: switching the disk to assets now works for me as well and everything is playing nicely as it should. Thanks all for your work on this!
